language: objective-c 
osx_image: xcode9.3
script:
- xctool clean build -workspace Mathematical-Surfaces.xcodeproj -scheme Mathematical-Surfaces -sdk iphonesimulator | xcpretty
- xcodebuild test -workspace Mathematical-Surfaces.xcodeproj -scheme Mathematical-Surfaces -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.3' | xcpretty