language: objective-c 
osx_image: xcode9.3
script:
- xctool clean build -project Mathematical-Surfaces.xcodeproj -scheme MathematicalSurfaces-iOS -sdk iphonesimulator | xcpretty
- xcodebuild test -project Mathematical-Surfaces.xcodeproj -scheme MathematicalSurfaces-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.3' | xcpretty